version: "3.7"
services:
  app:
    image: node
    volumes:
      - "./app:/mnt/app"
    working_dir: "/mnt/app"
    environment:
      PORT: '3000'
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm start || (\
          echo '⛔ `npm start` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports: [ 3000:3000 ]

  auth:
    image: node
    volumes:
      - './auth:/mnt/auth'
    working_dir: '/mnt/auth'
    environment:
      PORT: '5000'
      SECURE_KEY: 'D9C01532BD25898DDFB6A04FEC7EB84948B1F4F4E2E73199F221AD3EED1A99C5,C63BBC1884AD649D63607D8ACCE91AE9530DB7903FC377973E922E47A93C82E0'
      AUTH_URL: ${AUTH_URL:-https://auth.lvh.me:433}
      TRACKER_APP_URL: ${TRACKER_APP_URL:-https://tracker.lvh.me}
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm run start
    ports: [ 19229:19229, 5000:5000 ]

  sync:
    image: node
    volumes:
      - "./sync:/mnt/sync"
    working_dir: "/mnt/sync"
    environment:
      PORT: '5000'
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm start || (\
          echo '⛔ `npm start` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports: [ 4000:4000 ]
