parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020 # Allows for the parsing of modern ECMAScript features
  sourceType: "module" # Allows for the use of imports
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "detect"
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

  # Enables eslint-plugin-prettier and eslint-config-prettier.
  # This will display prettier errors as ESLint errors.
  # Make sure this is always the last configuration in the extends array.
  - "plugin:prettier/recommended"
rules:
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  